source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.5"

gem "rails",           "8.0.2"
gem "sassc-rails",     "2.1.2"
gem "sprockets-rails", "3.5.2"
gem "importmap-rails", "2.2.2"
gem "turbo-rails",     "2.0.16"
gem "stimulus-rails",  "1.0.4"
gem "jbuilder",        "2.14.1"
gem "puma",            "5.6.4"
gem "bootsnap",        "1.12.0", require: false

gem "ostruct"


group :development, :test do
  gem "sqlite3", "~> 2.7.3"
  gem "debug",   "~> 1.8", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console", "4.2.0"
end

group :test do
  gem "capybara",           "3.37.1"
  gem "selenium-webdriver", "4.2.0"
  gem "webdrivers",         "5.0.0"
end

group :production do
  gem "pg", "1.6.1"
end